import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Outfit } from 'next/font/google'
import Navbar from '@/components/Navbar'


const outfit = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EEdzy Couriers',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
     <ClerkProvider>
    <html lang="en">
      <body className={outfit.className}>
        <Navbar />
        {children}
        </body>
    </html>
    </ClerkProvider>
  )
}
